
language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/peregrine
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/tmhmm
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/epitope-prediction
  - richelbilderbeek/epiprepreds
  - richelbilderbeek/netmhc2pan
  - richelbilderbeek/nmhc2ppreds
  - richelbilderbeek/bbbq

rror: Failed to install 'bbbq' from GitHub:

  (converted from warning) packages ‘tmhmm’, ‘nmhc2ppreds’, ‘netmhc2pan’, ‘msa’, ‘epiprepreds’, ‘Biostrings’ are not available (for R version 4.0.2)

before_script:
  - sudo apt install python3-pip
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"
  - Rscript -e "pureseqtmr::install_pureseqtm()"

after_script:
  - make clean
  - make
  - ls *.csv

after_success:
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

after_failure:
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf

