language: r
dist: bionic
cache: packages

r_github_packages:
  - jtextor/epitope-prediction
  - richelbilderbeek/mhcnuggetsr
  - richelbilderbeek/mhcnpreds
  - richelbilderbeek/pureseqtmr
  - richelbilderbeek/bbbq


before_script:
  - sudo apt install python3-pip
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"
  - Rscript -e "pureseqtmr::install_pureseqtm()"

after_script:
  - make clean
  - make
  - ls *.csv

after_success:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_failure:
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

